# Generated by Django 3.2.18 on 2023-04-19 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50, unique=True)),
                ('companyEmail', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='web3User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('is_event_host', models.BooleanField(default=False)),
                ('is_GEA', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web3User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30)),
                ('eventSymbol', models.CharField(max_length=30)),
                ('eventLocation', models.CharField(max_length=30)),
                ('eventStartDate', models.DateField()),
                ('eventEndDate', models.DateField()),
                ('eventType', models.CharField(max_length=30)),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhost.web3user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhost.web3user')),
            ],
        ),
    ]
