# Generated by Django 3.2.18 on 2023-04-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='wallet_address',
            field=models.CharField(default='Na', max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
