# Generated by Django 3.2.18 on 2023-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0002_signuprequest_wallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuprequest',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='password2',
            field=models.CharField(default='Na', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='companyName',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
