# Generated by Django 3.2.18 on 2023-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0003_auto_20230419_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='eventEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='eventStartDate',
            field=models.DateTimeField(),
        ),
    ]
