# Generated by Django 3.2.18 on 2023-04-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0005_alter_eventrequest_eventsymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='eventName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
