# Generated by Django 3.2.18 on 2023-04-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='wallet_address',
            new_name='event_host',
        ),
    ]
