# Generated by Django 3.2.18 on 2023-04-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_wallet_address_event_event_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web3user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='web3User',
        ),
    ]
